apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: gitlab-managed-apps
  labels:
    app: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: database
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: clyde.local:5005/taliesin/micro-database/master
          ports:
            - containerPort: 8080
