apiVersion: v1
kind: Service
metadata:
  name: database-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: database-dev-api
  namespace: gitlab-managed-apps
spec:
  selector:
    app: database-dev
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
