apiVersion: v1
kind: Service
metadata:
  name: database-api
  namespace: gitlab-managed-apps
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: database-api-dev
  namespace: gitlab-managed-apps
  labels:
    app: database-dev
spec:
  selector:
    app: database-dev
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
